mercado/base/urls.py
from django.urls import path

from mercado.base.views import home, cadastro, perfil, editar_perfil, quem_somos_nos, politica_de_privacidade, \
    politica_de_entrega, trocas_e_devolucoes, politicas_de_cancelamentos_e_ressarcimentos, \
    politica_de_venda_precos_ofertas_e_promocoes, central_de_atendimento, pagamento_sucesso, pagamento_falha

app_name = 'base'
urlpatterns = [
    path('', home, name='home'),
    path('accounts/cadastro/', cadastro, name='cadastro'),
    path('perfil/', perfil, name='perfil'),
    path('perfil/editar_perfil', editar_perfil, name='editar_perfil'),
    path('quem_somos_nos', quem_somos_nos, name='quem_somos_nos'),
    path('politica_de_privacidade', politica_de_privacidade, name='politica_de_privacidade'),
    path('politica_de_entrega', politica_de_entrega, name='politica_de_entrega'),
    path('trocas_e_devolucoes', trocas_e_devolucoes, name='trocas_e_devolucoes'),
    path('politicas_de_cancelamentos_e_ressarcimentos', politicas_de_cancelamentos_e_ressarcimentos,
         name='politicas_de_cancelamentos_e_ressarcimentos'),
    path('politica_de_venda_precos_ofertas_e_promocoes', politica_de_venda_precos_ofertas_e_promocoes,
         name='politica_de_venda_precos_ofertas_e_promocoes'),
    path('central_de_atendimento', central_de_atendimento, name='central_de_atendimento'),
    path('pagamento_sucesso', pagamento_sucesso, name='pagamento_sucesso'),
    path('pagamento_falha', pagamento_falha, name='pagamento_falha'),
]

mercado/produtos/urls.py
from django.urls import path

from mercado.produtos.views import produto, pagina_de_marcas, pagina_de_departamentos, pagina_de_categorias, \
    pagina_de_subcategorias, pagina_de_pesquisa, pagina_do_carrinho, adicionar_ao_carrinho, remover_do_carrinho, \
    excluir_do_carrinho, pagina_dos_favoritos, adicionar_aos_favoritos, remover_dos_favoritos

app_name = 'produtos'
urlpatterns = [
    path('<slug:departamento>/<slug:categoria>/<slug:subcategoria>/<slug:slug>', produto, name='produto'),
    path('produtos-<str:marca>', pagina_de_marcas, name='pagina_de_marcas'),
    path('<slug:departamento>', pagina_de_departamentos, name='pagina_de_departamentos'),
    path('<slug:departamento>/<slug:categoria>', pagina_de_categorias, name='pagina_de_categorias'),
    path('<slug:departamento>/<slug:categoria>/<slug:subcategoria>', pagina_de_subcategorias,
         name='pagina_de_subcategorias'),
    path('search/', pagina_de_pesquisa, name='pagina_de_pesquisa'),
    path('carrinho/', pagina_do_carrinho, name='pagina_do_carrinho'),
    path('carrinho/adicionar/<int:produto_id>/', adicionar_ao_carrinho, name='adicionar_ao_carrinho'),
    path('carrinho/remover/<int:produto_id>/', remover_do_carrinho, name='remover_do_carrinho'),
    path('carrinho/excluir/<int:produto_id>/', excluir_do_carrinho, name='excluir_do_carrinho'),
    path('favoritos/', pagina_dos_favoritos, name='pagina_dos_favoritos'),
    path('favoritos/adicionar/<int:produto_id>/', adicionar_aos_favoritos, name='adicionar_aos_favoritos'),
    path('favoritos/remover/<int:produto_id>/', remover_dos_favoritos, name='remover_dos_favoritos'),
]

mercado/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mercado.base.urls')),
    path('', include('mercado.produtos.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.append(
        path('__debug__/', include(debug_toolbar.urls))
    )

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mercado/base/models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.core.mail import send_mail
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given username, email, and password.
        """
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """
    App base User class.

    E-mail and password are required. Other fields are optional.
    """
    first_name = models.CharField(_("first name"), max_length=150)
    last_name = models.CharField(_("last name"), max_length=150, null=True)
    date_of_birth = models.DateField(_("date of birth"), max_length=10, null=True)
    email = models.EmailField(_("email address"), unique=True)
    cpf = models.CharField(_("cpf"), max_length=14, unique=True, null=True)
    phone_number = models.CharField(_("phone number"), max_length=16, null=True)
    password = models.CharField(_("password"), max_length=150)
    is_staff = models.BooleanField(
        _("staff status"),
        default=False,
        help_text=_("Designates whether the user can log into this admin site."),
    )
    is_active = models.BooleanField(
        _("active"),
        default=True,
        help_text=_(
            "Designates whether this user should be treated as active. "
            "Unselect this instead of deleting accounts."
        ),
    )
    date_joined = models.DateTimeField(_("date joined"), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = "email"
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _("user")
        verbose_name_plural = _("users")

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = "%s %s" % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

mercado/base/forms.py
import re

from django import forms
from django.core.exceptions import ValidationError

from mercado.base.models import User
from django.utils.translation import gettext_lazy as _


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'date_of_birth', 'email', 'cpf', 'phone_number', 'password')

        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nome'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Sobrenome'}),
            'date_of_birth': forms.DateInput(
                attrs={'class': 'form-control', 'placeholder': 'Data de Nascimento: (ex: 00/00/0000)'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'E-mail'}),
            'cpf': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'CPF (ex: 000.000.000-00)'}),
            'phone_number': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': 'Número de Telefone: (ex: 99 99999-9999)'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Senha'}),
        }

    error_messages = {
        'first_name': {
            'nome_curto': _('Seu Nome precisa ter no mínimo 2 caracteres.'),
            'caracteres_invalidos': _('Os caracteres são inválidos, use apenas letras.')
        },
        'last_name': {
            'nome_curto': _('Seu Nome precisa ter no mínimo 2 caracteres.'),
            'caracteres_invalidos': _('Os caracteres são inválidos, use apenas letras.')
        },
        'cpf': {
            'cpf_invalido': _('Por favor insira um CPF válido.'),
        },
        'phone_number': {
            'numero_invalido': _('Por favor insira um número de telefone válido.'),
        },
        'password': {
            'numeros_e_letras': _('Sua senha deve conter números e letras.'),
            'senha_curta': _('Sua senha deve conter no mínimo 8 caracteres.'),
        },
    }

    def clean_first_name(self):
        first_name = self.cleaned_data.get('first_name')
        if not ''.join(first_name.split()).isalpha():
            raise ValidationError(self.error_messages['first_name']['caracteres_invalidos'])
        if len(first_name) < 2:
            raise ValidationError(self.error_messages['first_name']['nome_curto'])
        return first_name

    def clean_last_name(self):
        last_name = self.cleaned_data.get('last_name')
        if not ''.join(last_name.split()).isalpha():
            raise ValidationError(self.error_messages['cpf']['caracteres_invalidos'])
        if len(last_name) < 2:
            raise ValidationError(self.error_messages['last_name']['nome_curto'])
        return last_name

    def clean_cpf(self):
        cpf = self.cleaned_data.get('cpf')
        if not ''.join(re.split('[.-]', cpf)).isnumeric():
            raise ValidationError(self.error_messages['cpf']['cpf_invalido'])
        if not len(''.join(re.split('[.-]', cpf))) == 11:
            raise ValidationError(self.error_messages['cpf']['cpf_invalido'])
        return cpf

    def clean_phone_number(self):
        phone_number = self.cleaned_data.get('phone_number')
        if not ''.join(re.split('[ -]', phone_number)).isnumeric():
            raise ValidationError(self.error_messages['phone_number']['numero_invalido'])
        if not len(''.join(re.split('[ -]', phone_number))) == 11:
            raise ValidationError(self.error_messages['phone_number']['numero_invalido'])
        return phone_number

    def clean_password(self):
        password = self.cleaned_data.get('password')
        if not len(password) >= 8:
            raise ValidationError(self.error_messages['password']['senha_curta'])
        if password.isalpha() or password.isnumeric():
            raise ValidationError(self.error_messages['password']['numeros_e_letras'])
        return password

mercado/base/views.py
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password
from django.shortcuts import render, redirect

from mercado.base.forms import UserForm
from mercado.base.models import User


def home(request):
    return render(request, 'base/home.html')


def cadastro(request):
    if request.method == 'GET':
        form = UserForm
        return render(request, 'base/cadastro.html', context={'form': form})
    elif request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            user = User.objects.get(email=form.cleaned_data['email'])
            user.password = make_password(form.cleaned_data['password'])
            user.save()
            login(request, user=user)
            return redirect('/')
        else:
            return render(request, 'base/cadastro.html', context={'form': form})


@login_required
def perfil(request):
    return render(request, 'base/perfil.html', context={})


@login_required
def editar_perfil(request):
    if request.method == 'GET':
        user = request.user
        form = UserForm(instance=user)
        return render(request, 'base/editar_perfil.html', context={'form': form, 'user': user})
    elif request.method == 'POST':
        user = request.user
        form = UserForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            return redirect('/')
        else:
            return render(request, 'base/editar_perfil.html', context={'form': form})


def quem_somos_nos(request):
    return render(request, 'base/quem_somos_nos.html')


def politica_de_privacidade(request):
    return render(request, 'base/politica_de_privacidade.html')


def politica_de_entrega(request):
    return render(request, 'base/politica_de_entrega.html')


def trocas_e_devolucoes(request):
    return render(request, 'base/trocas_e_devolucoes.html')


def politicas_de_cancelamentos_e_ressarcimentos(request):
    return render(request, 'base/políticas_de_cancelamentos_e_ressarcimentos.html')


def politica_de_venda_precos_ofertas_e_promocoes(request):
    return render(request, 'base/política_de_venda_preços_ofertas_e_promoções.html')


def central_de_atendimento(request):
    return render(request, 'base/central_de_atendimento.html')


def pagamento_sucesso(request):
    return render(request, 'base/pagamento_sucesso.html')


def pagamento_falha(request):
    return render(request, 'base/pagamento_falha.html')

mercado/base/templates/base/card_produtos.html
{% load static %}
<div class="col-md-2 my-2">
    <div class="card border-0 text-center" style="box-shadow: 0 0 5px rgba(0, 0, 0, 0.3)">
        {% if produto in PRODUTOS_FAVORITOS %}
        <a class="" style="text-align: right"
           href="{% url 'produtos:remover_dos_favoritos' produto_id=produto.id %}">
            <img src="{% static 'img/icone-coracao-preenchido.webp' %}" class="card-img-top"
                 style="object-fit: contain; width: 48px; padding: 4px;" alt="teste">
        </a>
        {% else %}
        <a class="" style="text-align: right"
           href="{% url 'produtos:adicionar_aos_favoritos' produto_id=produto.id %}">
            <img src="{% static 'img/icone-coracao.webp' %}" class="card-img-top"
                 style="object-fit: contain; width: 48px; padding: 4px;" alt="teste">
        </a>
        {% endif %}

        <a class="text-decoration-none ratio ratio-1x1" href="{{ produto.get_absolute_url }}">
            <img src="{{ produto.imagem.url }}" class="card-img-top" style="object-fit: contain" alt="teste">
        </a>
        <div class="card-body">
            <div>
                <div style="height: 80px">
                    <a class="text-decoration-none" href="{{ produto.get_absolute_url }}">
                        <p class="card-text text-muted">{{ produto.nome }}</p></a>
                </div>
            </div>
            <h5 class="card-title text-success"><b>R$ {{ produto.preco }}</b></h5>
            <a class="btn btn-warning" href="{% url 'produtos:adicionar_ao_carrinho' produto_id=produto.id %}">
                Adicionar ao carrinho
            </a>
        </div>
    </div>
</div>

mercado/base/templates/base/carrossel.html
{% load static %}
<!-- Carrossel -->
<div class="row margem-carrossel" style="margin-bottom: 15px">
    <div id="carouselExampleIndicators" class="carousel slide">
        <div class="carousel-indicators">
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0"
                    class="active"
                    aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1"
                    aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2"
                    aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="{% static 'img/volta-as-aulas.webp' %}" class="d-block w-100" alt="Primeiro">
            </div>
            <div class="carousel-item">
                <img src="{% static 'img/ofertas-bubbaloo.webp' %}" class="d-block w-100" alt="Segundo">
            </div>
            <div class="carousel-item">
                <img src="{% static 'img/oferta-all-nutri.webp' %}" class="d-block w-100" alt="Terceiro">
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators"
                data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators"
                data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
</div>

mercado/base/templates/base/central_de_atendimento.html
{% extends 'base/base.html' %}
{% load static %}
{% block body %}

<div class="text-center text-muted mt-4 mb-4">
    <div class="row" style="margin-top: 10px">
        <div class="col-2"></div>
        <div class="col">

            <h3>Central de Atendimento</h3>

            <br>

            <h5 style="text-align: justify">1. Introdução</h5>
            <p style="text-align: justify">
                Bem-vindo à Central de Atendimento do Comercial Alegria! Estamos aqui para ajudá-lo da melhor forma
                possível. Se você tiver dúvidas, sugestões ou solicitação de suporte, entre em contato conosco através
                de um dos canais abaixo:
            </p>

            <br>

            <h5 style="text-align: justify">2. Telefone</h5>
            <p style="text-align: justify">
                Atendimento de segunda a sexta, das 8h às 18h através do telefone (69) 99363-6619.
            </p>

            <br>

            <h5 style="text-align: justify">3. WhatsApp</h5>
            <p style="text-align: justify">
                Envie uma mensagem para nosso WhatsApp (69) 99363-6619 e fale diretamente com um de nossos atendentes.
            </p>

            <br>

            <h5 style="text-align: justify">4. E-mail</h5>
            <p style="text-align: justify">
                Para dúvidas ou sugestões, envie um e-mail para: <br>atendimento@comercialalegria.com
            </p>

            <br>

            <h5 style="text-align: justify">5. Atendimento Presencial</h5>
            <p style="text-align: justify">
                Visite nossa loja para um atendimento personalizado:<br>
                Endereço: Av. Monte Negro, 312-380, Buritis - RO, 76880-000
            </p>

        </div>
        <div class="col-2"></div>

    </div>
</div>
{% endblock body %}

mercado/base/templates/base/editar_perfil.html
{% extends 'base/base.html' %}
{% load static %}
{% block body %}
<div class="row margem-carrossel">
    <div class="mt-2"></div>
    <div class="col-md-4"></div>
    <div class="col-md-4">
        <ul class="nav nav-tabs" id="myTab" role="tablist">

            <li class="nav-item" role="presentation">
                <button class="nav-link active" id="cadastro-tab" data-bs-toggle="tab"
                        data-bs-target="#cadastro-tab-pane"
                        type="button"
                        role="tab" aria-controls="profile-tab-pane" aria-selected="true">Editar Perfil
                </button>
            </li>
        </ul>
        <div class="tab-content" id="myTabContent">
            <div class="tab-pane fade show active" id="cadastro-tab-pane" role="tabpanel" aria-labelledby="profile-tab"
                 tabindex="0">
                <h4 class="text-center text-muted mt-4"><b>Editar Perfil</b></h4>
                <div class="form-group mt-4">
                    <form action="" method="POST">
                        {% csrf_token %}

                        <div class="mb-4">
                            {{ form.first_name }}
                            {% for error in form.first_name.errors %}
                            <div style="color: red">{{ error }}</div>
                            {% endfor %}
                        </div>

                        <div class="mb-4">
                            {{ form.last_name }}
                            {% for error in form.last_name.errors %}
                            <div style="color: red">{{ error }}</div>
                            {% endfor %}
                        </div>

                        <div class="mb-4">
<!--                            {{ form.date_of_birth }}-->
                            <input type="date" name="date_of_birth" class="form-control"
                                   value="{{form.date_of_birth.value|stringformat:'s'}}"
                                   maxlength="10" required id="id_date_of_birth">
                            {% for error in form.date_of_birth.errors %}
                            <div style="color: red">{{ error }}</div>
                            {% endfor %}
                        </div>

                        <div class="mb-4">
                            {{form.email }}
                            {% for error in form.email.errors %}
                            <div style="color: red">{{ error }}</div>
                            {% endfor %}
                        </div>

                        <div class="mb-4">
                            {{ form.cpf }}
                            {% for error in form.cpf.errors %}
                            <div style="color: red">{{ error }}</div>
                            {% endfor %}
                        </div>

                        <div class="mb-4">
                            {{ form.phone_number }}
                            {% for error in form.phone_number.errors %}
                            <div style="color: red">{{ error }}</div>
                            {% endfor %}
                        </div>

                        <div class="mb-4" style="display: none">
                            <input type="password" name="password" class="form-control"
                                   value="{{user.password}}" maxlength="16" required id="id_password">
                            {% for error in form.password.errors %}
                            <div style="color: red">{{ error }}</div>
                            {% endfor %}
                        </div>
                        <div style="display: flex; justify-content: space-between">
                            <a class="btn btn-outline-success col-5 mt-4" href="{% url 'base:perfil' %}">Cancelar</a>
                            <input type="submit" value="Salvar Alterações" class="btn btn-success col-5 mt-4">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-4"></div>
</div>
{% endblock body %}

mercado/base/templates/base/footer.html
{% load static %}
<!-- rodapé 1 -->
<footer class="main-footer mt-5 pt-4 text-black" style="margin-bottom: 5px">
    <div class="container">
        <div class="row justify-content-between">
            <div class="col-md-3">
                <h3>Receba nossas ofertas</h3>
                <span>e novidades por E-mail!</span>
            </div>
            <div class="col">
                <form>
                    <div class="mb-3">
                        <input type="email" class="form-control" id="email"
                               aria-describedby="emailHelp" placeholder="E-mail*">
                    </div>
                    <div class="mb-3">
                        <input type="tel" class="form-control" id="telefone" placeholder="Telefone*">
                    </div>
                    <label>Ao clicar em Cadastrar você aceita os <a href="#">termos e condições</a></label>
                    <br>
                    <button type="submit" class="btn btn-primary mb-3">Cadastrar</button>
                </form>
            </div>
        </div>
    </div>

    <!-- rodapé 2 -->
    <div class="second-footer pt-3 pb-2">
        <div class="container">
            <div class="row">
                <div class="col-md-4">

                    <p><b>Sobre o Comercial Alegria</b></p>

                    <p style="line-height: 1.7">
                        <a href="{% url 'base:quem_somos_nos' %}"
                           style="text-decoration: none; color: inherit">Quem somos nós</a>
                        <br>
                        <a href="{% url 'base:politica_de_privacidade' %}"
                           style="text-decoration: none; color: inherit">Política de Privacidade</a>
                        <br>
                        <a href="{% url 'base:politica_de_entrega' %}"
                           style="text-decoration: none; color: inherit">Política de Entrega</a>
                        <br>
                        <a href="{% url 'base:trocas_e_devolucoes' %}"
                           style="text-decoration: none; color: inherit">Trocas e Devoluções</a>
                        <br>
                        <a href="{% url 'base:politicas_de_cancelamentos_e_ressarcimentos' %}"
                           style="text-decoration: none; color: inherit">Políticas de Cancelamentos e Ressarcimentos</a>
                        <br>
                        <a href="{% url 'base:politica_de_venda_precos_ofertas_e_promocoes' %}"
                           style="text-decoration: none; color: inherit">Política de Venda, Preços, Ofertas e
                            Promoções</a>
                    </p>
                </div>
                <div class="col-md-3">
                    <p><b>Entre em Contato</b></p>
                    <p style="line-height: 1.7">
                        <a href="{% url 'base:central_de_atendimento' %}"
                           style="text-decoration: none; color: inherit">Central de Atendimento</a>
                    </p>
                </div>
                <div class="col-md-3">

                </div>
                <div class="col-md-2">
                    <img src="{% static 'img/banner.webp' %}" style="display: block; padding: 10px; max-width: 150%"
                         class="float-right mx-auto" alt="imagem_rodapé">
                </div>
            </div>
        </div>
    </div>

    <!-- rodapé 3 -->
    <div class="bg-light p-3">
        <div class="container">
            <div class="row">
                <div class="col">
                    <p><b>Formas de Pagamento</b></p>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <img src="{% static 'img/logo-visa.webp' %}" style="margin-right: 10px" alt="imagem_rodapé"
                         height="25">
                    <img src="{% static 'img/logo-mastercard.webp' %}" style="margin-right: 10px" alt="imagem_rodapé"
                         height="25">
                    <img src="{% static 'img/logo-elo.webp' %}" style="margin-right: 10px" alt="imagem_rodapé"
                         height="25">
                    <img src="{% static 'img/logo-american-express.webp' %}" style="margin-right: 10px"
                         alt="imagem_rodapé" height="25">
                    <img src="{% static 'img/logo-hipercard.webp' %}" style="margin-right: 10px" alt="imagem_rodapé"
                         height="25">
                    <img src="{% static 'img/logo-pix.webp' %}" style="margin-right: 10px" alt="imagem_rodapé"
                         height="25">
                </div>
            </div>
        </div>
    </div>
</footer>

mercado/base/templates/base/home.html
{% extends 'base/base.html' %}
{% load static %}
{% block body %}

{% include 'base/carrossel.html' %}

<!-- divs dos produtos -->
<div class="text-muted text-center my-3">
    <h5><b>Ofertas da Semana</b></h5>
</div>
<div class="row" style="margin-top: 10px">
    {% for produto in PRODUTOS|slice:':6' %}
    {% include 'base/card_produtos.html' %}
    {% endfor %}
</div>

<!-- imagem solta -->
<div class="row" style="margin-left: 30px; margin-right: 30px">
    <div class="col-md-12" style="margin-top: 30px; margin-bottom: 30px">
        <img src="{% static 'img/img-goncalves.webp' %}" class="card-img-top" alt="teste">
    </div>
</div>

<!-- divs dos produtos 2 -->
<div class="text-muted text-center mb-3">
    <h5><b>Mais Vendidos</b></h5>
</div>
<div class="row" style="margin-top: 10px">
    {% for produto in PRODUTOS|slice:'6:12' %}
    {% include 'base/card_produtos.html' %}
    {% endfor %}
</div>

{% include 'base/carrossel_duplo.html' %}

<!-- divs dos produtos 3 - final -->
<div class="text-muted text-center my-3">
    <h5><b>Volte a Comprar</b></h5>
</div>
<div class="row" style="margin-top: 10px; margin-bottom: 30px">
    {% for produto in PRODUTOS|slice:'12:18' %}
    {% include 'base/card_produtos.html' %}
    {% endfor %}
</div>
{% endblock body %}

mercado/base/templates/base/perfil.html
{% extends 'base/base.html' %}
{% load static %}
{% block body %}
<div class="row margem-carrossel">
    <div class="mt-5"></div>
    <div class="col-2"></div>
    <div class="col-md-8">
        <h2 class="text-center text-muted mb-3"><b>Minha Conta</b></h2>
        <div>
            <ul style="list-style: none">
                <li style="display: inline-block">
                    <a class="btn"
                       style="margin: 15px; font-size: 16px; border: 1px solid #666; padding-right: 60px; padding-top: 12px; padding-bottom: 12px; width: 230px"
                       href="{% url 'base:editar_perfil' %}">
                        <img src="{% static 'img/icone-editar-usuario.webp' %}" width="40"
                             height="35"
                             style="margin-right: 4px">Editar Perfil</a>
                </li>
                <li style="display: inline-block">
                    <a class="btn"
                       style="margin: 15px; font-size: 16px; border: 1px solid #666; padding-right: 60px; padding-top: 12px; padding-bottom: 12px; width: 230px"
                       href="{% url 'password_change' %}">
                        <img src="{% static 'img/icone-cadeado.webp' %}" width="40"
                             height="35"
                             style="margin-right: 4px">Senha</a>
                </li>
                <li style="display: inline-block">
                    <a class="btn"
                       style="margin: 15px; font-size: 16px; border: 1px solid #666; padding-right: 60px; padding-top: 12px; padding-bottom: 12px; width: 230px"
                       href="{% url 'produtos:pagina_dos_favoritos' %}">
                        <img src="{% static 'img/icone-coracao.webp' %}" width="40"
                             height="35"
                             style="margin-right: 4px">Meus Favoritos</a>
                </li>
            </ul>
        </div>
        {% if user.is_authenticated %}
        <form method="post" action="{% url 'logout' %}" style="text-align: center">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger col-6">Sair</button>
        </form>
        {% endif %}
    </div>
    <div class="col-2"></div>
</div>
{% endblock body %}