mercado/base/urls.py
from django.urls import path

from mercado.base.views import home, cadastro, perfil, editar_perfil, quem_somos_nos, politica_de_privacidade, \
    politica_de_entrega, trocas_e_devolucoes, politicas_de_cancelamentos_e_ressarcimentos, \
    politica_de_venda_precos_ofertas_e_promocoes, central_de_atendimento, pagamento_sucesso, pagamento_falha

app_name = 'base'
urlpatterns = [
    path('', home, name='home'),
    path('accounts/cadastro/', cadastro, name='cadastro'),
    path('perfil/', perfil, name='perfil'),
    path('perfil/editar_perfil', editar_perfil, name='editar_perfil'),
    path('quem_somos_nos', quem_somos_nos, name='quem_somos_nos'),
    path('politica_de_privacidade', politica_de_privacidade, name='politica_de_privacidade'),
    path('politica_de_entrega', politica_de_entrega, name='politica_de_entrega'),
    path('trocas_e_devolucoes', trocas_e_devolucoes, name='trocas_e_devolucoes'),
    path('politicas_de_cancelamentos_e_ressarcimentos', politicas_de_cancelamentos_e_ressarcimentos,
         name='politicas_de_cancelamentos_e_ressarcimentos'),
    path('politica_de_venda_precos_ofertas_e_promocoes', politica_de_venda_precos_ofertas_e_promocoes,
         name='politica_de_venda_precos_ofertas_e_promocoes'),
    path('central_de_atendimento', central_de_atendimento, name='central_de_atendimento'),
    path('pagamento_sucesso', pagamento_sucesso, name='pagamento_sucesso'),
    path('pagamento_falha', pagamento_falha, name='pagamento_falha'),
]

mercado/produtos/urls.py
from django.urls import path

from mercado.produtos.views import produto, pagina_de_marcas, pagina_de_departamentos, pagina_de_categorias, \
    pagina_de_subcategorias, pagina_de_pesquisa, pagina_do_carrinho, adicionar_ao_carrinho, remover_do_carrinho, \
    excluir_do_carrinho, pagina_dos_favoritos, adicionar_aos_favoritos, remover_dos_favoritos

app_name = 'produtos'
urlpatterns = [
    path('<slug:departamento>/<slug:categoria>/<slug:subcategoria>/<slug:slug>', produto, name='produto'),
    path('produtos-<str:marca>', pagina_de_marcas, name='pagina_de_marcas'),
    path('<slug:departamento>', pagina_de_departamentos, name='pagina_de_departamentos'),
    path('<slug:departamento>/<slug:categoria>', pagina_de_categorias, name='pagina_de_categorias'),
    path('<slug:departamento>/<slug:categoria>/<slug:subcategoria>', pagina_de_subcategorias,
         name='pagina_de_subcategorias'),
    path('search/', pagina_de_pesquisa, name='pagina_de_pesquisa'),
    path('carrinho/', pagina_do_carrinho, name='pagina_do_carrinho'),
    path('carrinho/adicionar/<int:produto_id>/', adicionar_ao_carrinho, name='adicionar_ao_carrinho'),
    path('carrinho/remover/<int:produto_id>/', remover_do_carrinho, name='remover_do_carrinho'),
    path('carrinho/excluir/<int:produto_id>/', excluir_do_carrinho, name='excluir_do_carrinho'),
    path('favoritos/', pagina_dos_favoritos, name='pagina_dos_favoritos'),
    path('favoritos/adicionar/<int:produto_id>/', adicionar_aos_favoritos, name='adicionar_aos_favoritos'),
    path('favoritos/remover/<int:produto_id>/', remover_dos_favoritos, name='remover_dos_favoritos'),
]

mercado/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mercado.base.urls')),
    path('', include('mercado.produtos.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.append(
        path('__debug__/', include(debug_toolbar.urls))
    )

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mercado/produtos/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models import CASCADE, UniqueConstraint
from django.urls import reverse


class Produto(models.Model):
    nome = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    marca = models.CharField(max_length=64)
    codigo = models.CharField(max_length=20, unique=True)
    preco = models.DecimalField(max_digits=10, decimal_places=2)
    imagem = models.ImageField(upload_to='imagens_produtos/')
    descricao = models.TextField(null=True)
    subcategoria = models.ForeignKey('Subcategoria', on_delete=models.PROTECT, null=True)
    data_criacao = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.nome

    def get_absolute_url(self):
        return reverse('produtos:produto', args=(self.subcategoria.categoria.departamento.slug,
                                                 self.subcategoria.categoria.slug,
                                                 self.subcategoria.slug,
                                                 self.slug,))


class Subcategoria(models.Model):
    nome = models.CharField(max_length=32)
    slug = models.SlugField(unique=True)
    categoria = models.ForeignKey('Categoria', on_delete=models.PROTECT)
    data_criacao = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.nome

    def get_absolute_url(self):
        return reverse('produtos:pagina_de_subcategorias',
                       args=(self.categoria.departamento.slug, self.categoria.slug, self.slug))


class Categoria(models.Model):
    nome = models.CharField(max_length=32)
    slug = models.SlugField(unique=True)
    departamento = models.ForeignKey('Departamento', on_delete=models.PROTECT)
    data_criacao = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.nome

    def get_absolute_url(self):
        return reverse('produtos:pagina_de_categorias', args=(self.departamento.slug, self.slug))


class Departamento(models.Model):
    nome = models.CharField(max_length=32)
    slug = models.SlugField(unique=True)
    data_criacao = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.nome

    def get_absolute_url(self):
        return reverse('produtos:pagina_de_departamentos', args=(self.slug,))


class Carrinho(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=CASCADE)
    produtos = models.ManyToManyField(Produto, through='CarrinhoItem')

    def __str__(self):
        produtos = [item.nome for item in self.produtos.all()]
        return f'{self.user.id}: ({produtos})'


class CarrinhoItem(models.Model):
    produto = models.ForeignKey(Produto, on_delete=CASCADE)
    carrinho = models.ForeignKey(Carrinho, on_delete=CASCADE)
    quantidade = models.PositiveSmallIntegerField(default=1)

    @property
    def total(self):
        return self.quantidade * self.produto.preco

    def __str__(self):
        return self.produto.nome

    class Meta:
        constraints = [
            UniqueConstraint(fields=['carrinho', 'produto'], name="unique_carrinho__produto")
        ]


class Favoritos(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=CASCADE)
    produtos = models.ManyToManyField(Produto, through='ItemFavoritos')

    def __str__(self):
        produtos = [item.nome for item in self.produtos.all()]
        return f'{self.user.id}: ({produtos})'


class ItemFavoritos(models.Model):
    produto = models.ForeignKey(Produto, on_delete=CASCADE)
    favoritos = models.ForeignKey(Favoritos, on_delete=CASCADE)

    class Meta:
        constraints = [
            UniqueConstraint(fields=['favoritos', 'produto'], name="unique_favorito__produto")
        ]

mercado/produtos/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from mercado.base.api_mercado_pago import gerar_link_de_pagamento
from mercado.produtos import facade
from mercado.produtos.carrinho import calcular_total_itens, obter_carrinho_e_itens, \
    adicionar_produto_ao_carrinho, remover_produto_do_carrinho, excluir_produto_do_carrinho
from mercado.produtos.models import Produto, ItemFavoritos


def produto(request, departamento, categoria, subcategoria, slug):
    produto = facade.buscar_produto(slug)
    marca = produto.marca
    return render(request, 'produtos/produto_detalhe.html',
                  context={'departamento': produto.subcategoria.categoria.departamento.slug,
                           'categoria': produto.subcategoria.categoria.slug,
                           'subcategoria': produto.subcategoria.slug,
                           'produto': produto, 'marca': marca})


def pagina_de_departamentos(request, departamento):
    produtos = facade.listar_produtos_por_departamento(departamento)
    departamento = produtos[0].subcategoria.categoria.departamento.nome
    return render(request, 'produtos/produtos_por_departamento.html',
                  context={'produtos': produtos, 'departamento': departamento})


def pagina_de_categorias(request, departamento, categoria):
    produtos = facade.listar_produtos_por_categoria(categoria)
    categoria = produtos[0].subcategoria.categoria.nome
    return render(request, 'produtos/produtos_por_categoria.html',
                  context={'produtos': produtos, 'categoria': categoria})


def pagina_de_subcategorias(request, departamento, categoria, subcategoria):
    produtos = facade.listar_produtos_por_subcategoria(subcategoria)
    subcategoria = produtos[0].subcategoria.nome
    return render(request, 'produtos/produtos_por_subcategoria.html',
                  context={'produtos': produtos, 'subcategoria': subcategoria})


def pagina_de_marcas(request, marca):
    produtos = facade.listar_produtos_por_marca(marca)
    return render(request, 'produtos/produtos_por_marca.html',
                  context={'produtos': produtos, 'marca': marca})


def pagina_de_pesquisa(request):
    query = request.GET.get('search')
    produtos = facade.filtrar_produtos_pela_pesquisa(query)
    return render(request, 'produtos/produtos_por_pesquisa.html',
                  context={'produtos': produtos})


def pagina_do_carrinho(request):
    carrinho, carrinhoitens = obter_carrinho_e_itens(request)
    total = calcular_total_itens(carrinhoitens)
    link_de_compra = gerar_link_de_pagamento(request)
    return render(request, 'produtos/carrinho.html',
                  context={'carrinho': carrinho, 'carrinhoitens': carrinhoitens, 'total': total,
                           'link_de_compra': link_de_compra})


def adicionar_ao_carrinho(request, produto_id: int):
    carrinho, carrinhoitens = adicionar_produto_ao_carrinho(request, produto_id)
    total = calcular_total_itens(carrinhoitens)
    link_de_compra = gerar_link_de_pagamento(request)
    return render(request, 'produtos/carrinho.html',
                  context={'carrinho': carrinho, 'carrinhoitens': carrinhoitens, 'total': total,
                           'link_de_compra': link_de_compra})


def remover_do_carrinho(request, produto_id: int):
    carrinho, carrinhoitens = remover_produto_do_carrinho(request, produto_id)
    total = calcular_total_itens(carrinhoitens)
    link_de_compra = gerar_link_de_pagamento(request)
    return render(request, 'produtos/carrinho.html',
                  context={'carrinho': carrinho, 'carrinhoitens': carrinhoitens, 'total': total,
                           'link_de_compra': link_de_compra})


def excluir_do_carrinho(request, produto_id: int):
    carrinho, carrinhoitens = excluir_produto_do_carrinho(request, produto_id)
    total = calcular_total_itens(carrinhoitens)
    link_de_compra = gerar_link_de_pagamento(request)
    return render(request, 'produtos/carrinho.html',
                  context={'carrinho': carrinho, 'carrinhoitens': carrinhoitens, 'total': total,
                           'link_de_compra': link_de_compra})


@login_required
def pagina_dos_favoritos(request):
    try:
        favoritos = facade.buscar_favoritos_existente(request)
    except Exception:
        favoritos = facade.criar_favoritos(request)

    produtos = [objeto.produto for objeto in facade.listar_itens_dos_favoritos(favoritos)]

    return render(request, 'produtos/produtos_dos_favoritos.html',
                  context={'produtos': produtos})


@login_required
def adicionar_aos_favoritos(request, produto_id: int):
    try:
        favoritos = facade.buscar_favoritos_existente(request)
    except Exception:
        favoritos = facade.criar_favoritos(request)

    produto = Produto.objects.get(id=produto_id)

    try:
        facade.buscar_item_dos_favoritos(produto)
    except Exception:
        novo_item = ItemFavoritos(produto=produto, favoritos=favoritos)
        novo_item.save()

    produtos = [objeto.produto for objeto in facade.listar_itens_dos_favoritos(favoritos)]

    return render(request, 'produtos/produtos_dos_favoritos.html',
                  context={'produtos': produtos})


@login_required
def remover_dos_favoritos(request, produto_id: int):
    favoritos = facade.buscar_favoritos_existente(request)

    produto = Produto.objects.get(id=produto_id)

    try:
        item = facade.buscar_item_dos_favoritos(produto)
        item.delete()
    except Exception:
        pass

    produtos = [objeto.produto for objeto in facade.listar_itens_dos_favoritos(favoritos)]

    return render(request, 'produtos/produtos_dos_favoritos.html',
                  context={'produtos': produtos})

mercado/produtos/templates/produtos/carrinho.html
{% extends 'base/base.html' %}
{% load static %}
{% block body %}

<div class="container-fluid">
    <div style="height: 20px"></div>
    <div class="row">
        <div class="col">
            <table width="100%">
                <thead>
                <tr style="border-bottom: 3px solid #ccc">
                    <th style="text-align: left; padding-bottom: 10px; color: #666">PRODUTO</th>
                    <th style="text-align: left; padding-bottom: 10px; color: #666">PREÇO</th>
                    <th style="text-align: left; padding-bottom: 10px; color: #666">QUANTIDADE</th>
                    <th style="text-align: left; padding-bottom: 10px; color: #666">TOTAL</th>
                    <th style="text-align: left; padding-bottom: 10px; color: #666">EXCLUIR</th>
                </tr>
                </thead>

                <tbody>
                {% for item in carrinhoitens %}
                <tr style="border-bottom: 3px solid #ccc">
                    <td style="padding: 30px">
                        <div style="display: flex; align-items: center;">
                            <img src="{{ item.produto.imagem.url }}" width="150" height="150"
                                 style="border-radius: 4px; object-fit: contain">
                            <div style="margin-left: 20px">
                                <div style="font-size: 20px; margin-bottom: 10px">{{ item.produto.nome }}</div>
                                <div style="color: #666">Marca: {{ item.produto.marca }}</div>
                            </div>
                        </div>
                    </td>
                    <td style="padding: 30px">R${{ item.produto.preco }}</td>
                    <td style="padding: 30px">
                        <div class="qt-button">
                            <a class="custom-button" style="text-decoration: none; color: black; margin-right: 8px"
                               href="{% url 'produtos:remover_do_carrinho' produto_id=item.produto.id %}">-</a>
                            <span>{{ item.quantidade }}</span>
                            <a class="custom-button" style="text-decoration: none; color: black; margin-left: 8px"
                               href="{% url 'produtos:adicionar_ao_carrinho' produto_id=item.produto.id %}">+</a>
                        </div>
                    </td>
                    <td style="padding: 30px">R${{ item.total }}</td>
                    <td style="padding: 30px">
                        <a class="custom-button" style="text-decoration: none; color: black"
                           href="{% url 'produtos:excluir_do_carrinho' produto_id=item.produto.id %}">x</a>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

        <!-- Resumo da Compra -->
        <div class="col-4">
            <div class="box">
                <header style="padding: 15px 20px; font-size: 18px; border-bottom: 1px solid #ccc">RESUMO DA COMPRA
                </header>
                <div style="padding: 20px">
                    <div style="margin-bottom: 8px; display: flex; justify-content: space-between; color: #111"><span>Sub-Total</span><span>R${{ total }}</span>
                    </div>
                    <div style="display: flex; justify-content: space-between"><span>Frete</span><span>Gratis</span>
                    </div>
                </div>
                <footer style="padding: 15px 20px; font-size: 18px; background: #ddd; display: flex; justify-content: space-between">
                    <span>Total</span>
                    <span>R${{ total }}</span>
                </footer>
            </div>

            {% if request.user.is_authenticated and carrinhoitens|length > 0 %}
            <a class="btn col-6" href="{{ link_de_compra }}"
               style="background: green; border: 0; color: white; display: block; width: 100%; padding: 15px; letter-spacing: 1px">
                FINALIZAR COMPRA
            </a>
            {% elif not request.user.is_authenticated and carrinhoitens|length > 0 %}
            <a class="btn col-6" href="{% url 'base:cadastro' %}"
               style="background: green; border: 0; color: white; display: block; width: 100%; padding: 15px; letter-spacing: 1px">
                CADASTRE-SE PARA CONCLUIR A COMPRA
            </a>
            {% else %}
            <a class="btn col-6" href="{% url 'base:home' %}"
               style="background: green; border: 0; color: white; display: block; width: 100%; padding: 15px; letter-spacing: 1px">
                ADICIONE UM PRODUTO AO CARRINHO
            </a>
            {% endif %}

        </div>
    </div>
</div>

{% endblock body %}

mercado/produtos/templates/produtos/produto_detalhe.html
{% extends 'base/base.html' %}
{% load static %}
{% block body %}
<div class="row justify-content-center mt-4">
    <div class="col-md-10">
        <div>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a
                            href="{{ produto.subcategoria.categoria.departamento.get_absolute_url }}">
                        {{ produto.subcategoria.categoria.departamento.nome }}</a></li>
                    <li class="breadcrumb-item"><a href="{{ produto.subcategoria.categoria.get_absolute_url }}">
                        {{ produto.subcategoria.categoria.nome }}</a></li>
                    <li class="breadcrumb-item"><a href="{{ produto.subcategoria.get_absolute_url }}">
                        {{ produto.subcategoria.nome }}</a></li>
                </ol>
            </nav>
        </div>
        <div class="row">
            <div class="img-content col-12 col-lg-6 mt-3">
                <span class="ratio ratio-1x1">
                <img src="{{ produto.imagem.url }}" class="img-fluid " style="object-fit: contain"
                     alt="{{produto.nome}}">
                </span>
            </div>
            <div class="top-container-left-column col-12 col-lg-6 mt-3">
                <h4 class="mt-3"><b>{{ produto.nome | default:'(Nome do Produto Não Está Disponível)' }}</b></h4>
                <div class="row">
                    <div class="col-md-6">
                    <span class="">
                        <small>
                            Marca:
                            <a class="text-reset text-decoration-none"
                               href="{% url 'produtos:pagina_de_marcas' marca %}">
                                {{ produto.marca | default:'(Marca do Produto Não Está Disponível)' }}
                            </a>
                        </small>
                    </span>
                    </div>
                    <div class="col-md-6">
                        <span class="">
                            <small>
                                (Código: {{ produto.codigo | default:'(Código do Produto Não Está Disponível)' }})
                            </small>
                        </span>
                    </div>
                </div>
                <div class="row mt-5">
                    <div class="col">
                        <h2 class="text-success">
                            <b>
                                R$ {{ produto.preco | default:'(Preço do Produto Não Está Disponível)' }}
                            </b>
                        </h2>
                        <a type="button" class="btn btn-success col-12 mt-4"
                           href="{% url 'produtos:adicionar_ao_carrinho' produto_id=produto.id %}">Adicionar ao
                            carrinho</a>
                    </div>
                    <div style="border-bottom: 2px solid #888; border-top: 1px solid #888; margin: 20px">
                        <p class="mt-3" style="margin-bottom: 15px"><img
                                style="height: 20px; margin-right: 8px"
                                src="{% static 'img/caminhao-entrega.webp' %}"><small><b>Valor mínimo para compras R$
                            50,00</b></small>
                        </p>
                        <p><img style="height: 20px; margin-right: 8px" src="{% static 'img/frete.webp' %}">
                            <small><b>Disponível para retirada</b></small>
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col text-muted">
                <br>
                <h4><b>Descrição do Produto</b></h4>
                <h6>{{ produto.descricao | default:'(Descrição do Produto Não Está Disponível)' }}</h6>
            </div>
        </div>
    </div>
</div>
{% endblock body %}

mercado/produtos/templates/produtos/produtos_dos_favoritos.html
{% extends 'base/base.html' %}
{% load static %}
{% block body %}

<!-- produtos -->
<div class="text-center text-muted mt-4 mb-4">
    <h2><b>Meus Favoritos</b></h2>
</div>

<div class="row" style="margin-top: 10px">

    {% for produto in produtos %}
    {% include 'base/card_produtos.html' %}
    {% endfor %}

</div>

{% endblock body %}

mercado/produtos/templates/produtos/produtos_por_categoria.html
{% extends 'base/base.html' %}
{% load static %}
{% block body %}

<!-- produtos -->
<div class="text-center text-muted mt-4 mb-4">
    <h2><b>{{ categoria }}</b></h2>
</div>

<div class="row" style="margin-top: 10px">

    {% for produto in produtos %}
    {% include 'base/card_produtos.html' %}
    {% endfor %}

</div>

{% endblock body %}

mercado/produtos/templates/produtos/produtos_por_departamento.html
{% extends 'base/base.html' %}
{% load static %}
{% block body %}

<!-- produtos -->
<div class="text-center text-muted mt-4 mb-4">
    <h2><b>{{ departamento }}</b></h2>
</div>

<div class="row" style="margin-top: 10px">

    {% for produto in produtos %}
    {% include 'base/card_produtos.html' %}
    {% endfor %}

</div>

{% endblock body %}

mercado/produtos/templates/produtos/produtos_por_marca.html
{% extends 'base/base.html' %}
{% load static %}
{% block body %}

<!-- produtos -->
<div class="text-center text-muted mt-4 mb-4">
    <h2><b>{{ marca }}</b></h2>
</div>

<div class="row" style="margin-top: 10px">

    {% for produto in produtos %}
    {% include 'base/card_produtos.html' %}
    {% endfor %}

</div>

{% endblock body %}

mercado/produtos/templates/produtos/produtos_por_pesquisa.html
{% extends 'base/base.html' %}
{% load static %}
{% block body %}

<!-- produtos -->
<div class="text-center text-muted mt-4 mb-4">
    <h2><b>Resultados para "{{ request.GET.search }}"</b></h2>
</div>

<div class="row" style="margin-top: 10px">

    {% for produto in produtos %}
    {% include 'base/card_produtos.html' %}
    {% endfor %}

</div>

{% endblock body %}

mercado/produtos/templates/produtos/produtos_por_subcategoria.html
{% extends 'base/base.html' %}
{% load static %}
{% block body %}

<!-- produtos -->
<div class="text-center text-muted mt-4 mb-4">
    <h2><b>{{ subcategoria }}</b></h2>
</div>

<div class="row" style="margin-top: 10px">

    {% for produto in produtos %}
    {% include 'base/card_produtos.html' %}
    {% endfor %}

</div>

{% endblock body %}